# Generated by Django 4.1 on 2022-08-13 13:58

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerceapp', '0005_alter_product_seller'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, populate_from='title', unique_with=['title', 'date_created__month']),
        ),
    ]
