# Generated by Django 3.1.4 on 2020-12-29 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerceapp', '0009_auto_20201229_2149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartproduct',
            name='quantity',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='cartproduct',
            name='rate',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='cartproduct',
            name='subtotal',
            field=models.IntegerField(),
        ),
    ]
