# Generated by Django 3.1.5 on 2021-01-25 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerceapp', '0013_admin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('Order Recieved', 'Order Recieved'), ('Order Processing', 'Order Processing'), ('On the way', 'On the way'), ('Order Complete', 'Order Complete'), ('Order Cancel', 'Order Cancel')], default='Order Recieved', max_length=50),
        ),
    ]
